# Model Configuration File
# Each top-level key represents a model to train

xgboost:
  # Model initialization parameters
  init_params:
    n_estimators: 100
    max_depth: 6
    learning_rate: 0.3
    objective: "reg:squarederror"
    random_state: 42
  
  # Training parameters
  epochs: 10
  batch_size: 32
  learning_rate: 0.001  # For optimizer if applicable
  
  # Additional model-specific parameters
  early_stopping_rounds: 10
  eval_metric: "rmse"

lightgbm:
  init_params:
    objective: "regression"
    learning_rate: 0.05
    n_estimators: 1  # Start with 1 estimator
    num_leaves: 31
    metric: ["l2", "mae"]
    verbosity: -1
  epochs: 10

neural_network:
  init_params:
    hidden_size: 64
    learning_rate: 0.001
  epochs: 10
  batch_size: 32

svm:
  init_params:
    kernel: 'rbf'       # rbf, linear, poly, sigmoid
    C: 1.0              # Regularization parameter
    epsilon: 0.1        # Epsilon-tube for SVR
    gamma: 'scale'      # Kernel coefficient
  epochs: 1             # SVM trains fully in one epoch