# Model Configuration File
# Each top-level key represents a model to train

xgboost:
  init_params:
    objective: "reg:squarederror"
    # Hyperparameters to tune
    learning_rate: [0.01, 0.05, 0.1]  # Also called eta
    max_depth: [3, 5, 7]
    n_estimators: [100, 200, 500]
    subsample: [0.6, 0.8, 1.0]
    colsample_bytree: [0.6, 0.8, 1.0]
    gamma: [0, 0.1, 0.2]
  tuning:
    method: "random"  # Options: grid, random
    n_iter: 20        # For random search
    cv: 5             # Cross-validation folds
    scoring: "neg_mean_squared_error"
  epochs: 100        # More trees for better convergence

lightgbm:
  init_params:
    objective: "regression"
    learning_rate: 0.05
    n_estimators: 1  # Start with 1 estimator
    num_leaves: 31
    metric: ["l2", "mae"]
    verbosity: -1
  epochs: 10

neural_network:
  init_params:
    hidden_size: 64
    learning_rate: 0.001
  epochs: 10
  batch_size: 32

svm:
  init_params:
    kernel: 'rbf'       # rbf, linear, poly, sigmoid
    C: 1.0              # Regularization parameter
    epsilon: 0.1        # Epsilon-tube for SVR
    gamma: 'scale'      # Kernel coefficient
  epochs: 1             # SVM trains fully in one epoch

pinn:
  init_params:
    hidden_size: 64
    learning_rate: 0.001
    lambda_physics: 0.1
  epochs: 50
  batch_size: 32
  learning_rate: 0.001